### ISSUE TITLE
A ping from language-pfm

### ISSUE THREAD

**Issue by leipert** [mangecoeur/preview-inline#2] opened 2015-07-25 11:08 UTC
This is a ping, are you satisfied with the quality of `language-pfm`? Did you have any problems with it in the past?
Give me a pong, if any problems arose.

**Comment by mangecoeur** [comment] 2015-07-27 11:20
@leipert Thanks, it's be good so far... i did just come across the issue that inline math isn't highlighted inside tables, not sure if that's even possible though...

**Comment by anojo** [comment] 2015-08-04 15:39
I just tried it, thanks for this. When I type, for example "lalalal $2+2$", then put the cursor after the "2", press "Crtl+Alt+p", nice tooltip appears. Once I start adding more to the formula, the tooltip updates in real time but showing the "$" signs. If I then move the cursor outside the formula scope, it still  includes whatever I type next in the tooltip ("$2+2+3$ lala" for example), until I close it by clicking in the box. Am I not using it as intended, or is it a specific problem with my installation maybe?

**Comment by mangecoeur** [comment] 2015-08-04 15:43
@anojo hmm sounds like a bug with the markers used to track the math region. Have opened issue #7 to track this

**Comment by tonylee2016** [comment] 2015-10-19 01:43
Hi 

do you know how to achieve the same effect described by anojo in ".tex" file ?
sorry for any ambiguity, I am new to the editor

thanks a lot

**Comment by tonylee2016** [comment] 2015-10-19 01:48
somehow it is working right now

**Closed** 2017-06-25 15:12 UTC
